version: "3"

services:
  broker:
    command: redis-server --save 20 1 --loglevel warning
    container_name: "Etodo-Broker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: redis:7-bullseye
    ports:
      - "6379:6379"
    restart: always

  worker:
    build: ./etodo_api
    command: bash -c "cd src && celery -A etodo worker --loglevel=info"
    container_name: "Etodo-Worker"
    environment:
      ETODO_ENV: ${ETODO_ENV:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: etodo:api
    restart: always
    volumes:
      - ./etodo_api:/etodo
    depends_on:
      - broker

  beat:
    build: ./etodo_api
    command: bash -c "cd src && celery -A etodo beat --loglevel=info"
    container_name: "EtodoBeat"
    environment:
      ETODO_ENV: ${ETODO_ENV:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: etodo:api
    restart: always
    volumes:
      - ./etodo_api:/etodo
    depends_on:
      - worker

  api:
    build: ./etodo_api
    command: gunicorn etodo.wsgi:application --chdir=/etodo/src -b=0.0.0.0:8000 -w=4 -t=10
    container_name: "Etodo-Backend"
    environment:
      ETODO_ENV: ${ETODO_ENV:-development}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
     - "8000:8000"
    image: etodo:api
    restart: always
    volumes:
      - ./etodo_api:/etodo
    depends_on:
      - beat

  # webui:
  #   build: ./etodo_webui
  #   command: bash -c "npm run build && npm start"
  #   container_name: "etodo-Frontend"
  #   environment:
  #     NODE_ENV: ${NODE_ENV:-local}
  #   image: etodo:webui
  #   restart: always
  #   volumes:
  #     - ./etodo_webui:/etodo
  #     - /etodo/node_modules/
  #   depends_on:
  #     - api

  # nginx:
  #   container_name: "etodo-Nginx"
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./etodo_api/static:/static
  #     - ./etodo_webui/.next:/.next
  #     - ./certs:/etc/ssl/certs
  #   depends_on:
  #     - webui
