# Generated by Django 4.2.3 on 2023-07-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_task_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
    ]
